export const languages = () => {
    return [
        { value: 'Afrikaans', text: 'Afrikaans' },
        { value: 'Albanian', text: 'Albanian' },
        { value: 'Arabic', text: 'Arabic' },
        { value: 'Bengali', text: 'Bengali' },
        { value: 'Bulgarian', text: 'Bulgarian' },
        { value: 'Catalan', text: 'Catalan' },
        { value: 'Chinese (Simplified)', text: 'Chinese (Simplified)' },
        { value: 'Chinese (Traditional)', text: 'Chinese (Traditional)' },
        { value: 'Croatian', text: 'Croatian' },
        { value: 'Czech', text: 'Czech' },
        { value: 'Danish', text: 'Danish' },
        { value: 'Dutch', text: 'Dutch' },
        { value: 'English', text: 'English' },
        { value: 'Estonian', text: 'Estonian' },
        { value: 'Finnish', text: 'Finnish' },
        { value: 'French', text: 'French' },
        { value: 'German', text: 'German' },
        { value: 'Greek', text: 'Greek' },
        { value: 'Gujarati', text: 'Gujarati' },
        { value: 'Haitian Creole', text: 'Haitian Creole' },
        { value: 'Hebrew', text: 'Hebrew' },
        { value: 'Hindi', text: 'Hindi' },
        { value: 'Hungarian', text: 'Hungarian' },
        { value: 'Icelandic', text: 'Icelandic' },
        { value: 'Indonesian', text: 'Indonesian' },
        { value: 'Irish', text: 'Irish' },
        { value: 'Italian', text: 'Italian' },
        { value: 'Japanese', text: 'Japanese' },
        { value: 'Kannada', text: 'Kannada' },
        { value: 'Korean', text: 'Korean' },
        { value: 'Latvian', text: 'Latvian' },
        { value: 'Lithuanian', text: 'Lithuanian' },
        { value: 'Macedonian', text: 'Macedonian' },
        { value: 'Malay', text: 'Malay' },
        { value: 'Malayalam', text: 'Malayalam' },
        { value: 'Maltese', text: 'Maltese' },
        { value: 'Marathi', text: 'Marathi' },
        { value: 'Norwegian', text: 'Norwegian' },
        { value: 'Persian', text: 'Persian' },
        { value: 'Polish', text: 'Polish' },
        { value: 'Portuguese', text: 'Portuguese' },
        { value: 'Punjabi', text: 'Punjabi' },
        { value: 'Romanian', text: 'Romanian' },
        { value: 'Russian', text: 'Russian' },
        { value: 'Serbian', text: 'Serbian' },
        { value: 'Slovak', text: 'Slovak' },
        { value: 'Slovenian', text: 'Slovenian' },
        { value: 'Spanish', text: 'Spanish' },
        { value: 'Swahili', text: 'Swahili' },
        { value: 'Swedish', text: 'Swedish' },
        { value: 'Tamil', text: 'Tamil' },
        { value: 'Telugu', text: 'Telugu' },
        { value: 'Thai', text: 'Thai' },
        { value: 'Turkish', text: 'Turkish' },
        { value: 'Ukrainian', text: 'Ukrainian' },
        { value: 'Urdu', text: 'Urdu' },
        { value: 'Vietnamese', text: 'Vietnamese' },
        { value: 'Welsh', text: 'Welsh' },
        { value: 'Yiddish', text: 'Yiddish' }
    ];
}